(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},c="undefined"!==typeof module&&module.exports,b="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,d=function(){for(var b,d=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],f=0,c=d.length,h={};f<c;f++)if((b=d[f])&&b[1]in a){for(f=0;f<b.length;f++)h[d[0][f]]=
b[f];return h}return!1}(),g={change:d.fullscreenchange,error:d.fullscreenerror},h={request:function(e){var c=d.requestFullscreen;e=e||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))e[c]();else e[c](b&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[d.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(b,d){var f=g[b];f&&a.addEventListener(f,d,!1)},off:function(b,
d){var f=g[b];f&&a.removeEventListener(f,d,!1)},raw:d};d?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!a[d.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[d.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!a[d.fullscreenEnabled]}}}),c?module.exports=h:window.screenfull=h):c?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var g=b.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var h=b.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";g.appendChild(h);d.insertBefore(g,b.head);
a=7==h["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(g)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function inIframe(){try{return window.self!==window.top}catch(a){return!0}}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width");_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b;if(b<a){var g=a-b;b+=g;d+=CANVAS_WIDTH/CANVAS_HEIGHT*g}else d<c&&(g=c-d,d+=g,b+=CANVAS_HEIGHT/CANVAS_WIDTH*g);g=a/2-b/2;var h=c/2-d/2,e=CANVAS_WIDTH/d;if(h*e<-EDGEBOARD_X||g*e<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,g=(a-b)/2,h=(c-d)/2,e=CANVAS_WIDTH/d;s_iOffsetX=-1*h*e;s_iOffsetY=-1*g*e;0<=g&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oSelectPlayers&&s_oSelectPlayers.refreshButtonPos();s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*d,s_oStage.canvas.height=2*b,canvas.style.width=d+"px",canvas.style.height=
b+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",d+"px"),$("#canvas").css("height",b+"px")):(s_oStage.canvas.width=d,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(d/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>g?$("#canvas").css("top",g+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(c)}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),g=new createjs.Shape;c&&b?g.graphics.beginFill("#fff").drawRect(0,0,c,b):g.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=g;return d}function createSprite(a,c,b,d,g,h){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,g,h);a.hitArea=c;return a}function pad(a,c,b){a+="";return a.length>=c?a:Array(c-a.length+1).join(b||"0")+a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}
function bubbleSort(a){do{var c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}
function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),g=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+g*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+g*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,c){var b=getBounds(a,.9);var d=getBounds(c,.98);return calculateIntersection(b,d)}
function calculateIntersection(a,c){var b,d,g,h;var e=a.x+(b=a.width/2);var k=a.y+(d=a.height/2);var f=c.x+(g=c.width/2);var l=c.y+(h=c.height/2);e=Math.abs(e-f)-(b+g);k=Math.abs(k-l)-(d+h);return 0>e&&0>k?(e=Math.min(Math.min(a.width,c.width),-e),k=Math.min(Math.min(a.height,c.height),-k),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:e,height:k,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,g=d.length,h;for(h=0;h<g;h++){var e=getBounds(d[h],1);e.x<b.x&&(b.x=e.x);e.y<b.y&&(b.y=e.y);e.x+e.width>b.x2&&(b.x2=e.x+e.width);e.y+e.height>b.y2&&(b.y2=e.y+e.height)}Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{if(a instanceof createjs.Bitmap){g=
a.sourceRect||a.image;h=g.width*c;var k=g.height*c}else if(a instanceof createjs.Sprite)if(a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image){g=a.spriteSheet.getFrame(a.currentFrame);h=g.rect.width;k=g.rect.height;d=g.regX;var f=g.regY}else b.x=a.x||0,b.y=a.y||0;else b.x=a.x||0,b.y=a.y||0;d=d||0;h=h||0;f=f||0;k=k||0;b.regX=d;b.regY=f;g=a.localToGlobal(0-d,0-f);e=a.localToGlobal(h-d,k-f);h=a.localToGlobal(h-d,0-f);d=a.localToGlobal(0-d,k-f);b.x=
Math.min(Math.min(Math.min(g.x,e.x),h.x),d.x);b.y=Math.min(Math.min(Math.min(g.y,e.y),h.y),d.y);b.width=Math.max(Math.max(Math.max(g.x,e.x),h.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(g.y,e.y),h.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;if(a.type in b)document.body.className=b[a.type];else if(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className){if(s_oMain.stopUpdate(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.muted=!0}else s_oMain.startUpdate(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(createjs.Sound.muted=
!1)}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function ctlArcadeResume(){null!==s_oMain&&(s_oMain.startUpdate(),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(createjs.Sound.muted=!0)}function ctlArcadePause(){null!==s_oMain&&(s_oMain.stopUpdate(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(createjs.Sound.muted=!1))}function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var d=c[b].split("=");if(d[0]==a)return d[1]}}
function fullscreenHandler(){ENABLE_FULLSCREEN&&!inIframe()&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oSelectPlayers&&s_oSelectPlayers.resetFullscreenBut())}
if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oSelectPlayers&&s_oSelectPlayers.resetFullscreenBut()});
function CSpriteLibrary(){var a,c,b,d,g,h;this.init=function(e,k,f){b=c=0;d=e;g=k;h=f;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){g.call(h)};this._onSpriteLoaded=function(){d.call(h);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=256,EDGEBOARD_Y=84,PRIMARY_FONT="comfortaabold",FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,ENABLE_FULLSCREEN=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_SELECT_PLAYERS=4,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CARD_DEALED=6,ENABLE_CHECK_ORIENTATION,AD_SHOW_COUNTER,NUM_PLAYERS,STARTING_NUM_CARDS,CARD_WIDTH=156,CARD_HEIGHT=242,aHandPos=[];
aHandPos.num_player_2=[{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+350},{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-350}];aHandPos.num_player_3=[{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+350},{x:CANVAS_WIDTH/2-650,y:CANVAS_HEIGHT/2-40},{x:CANVAS_WIDTH/2+650,y:CANVAS_HEIGHT/2}];aHandPos.num_player_4=[{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2+350},{x:CANVAS_WIDTH/2-650,y:CANVAS_HEIGHT/2-40},{x:CANVAS_WIDTH/2,y:CANVAS_HEIGHT/2-350},{x:CANVAS_WIDTH/2+650,y:CANVAS_HEIGHT/2-40}];TEXT_GAMEOVER="CONGRATULATION! YOU WON!";
TEXT_LOSE="SORRY, THE PLAYER ";TEXT_LOSE2=" WON THIS GAME";TEXT_SCORE="YOUR SCORE";TEXT_RESTART="RESTART";TEXT_MOVES="MOVES";TEXT_ARE_SURE="ARE YOU SURE?";TEXT_SELECT_PLAYERS="SELECT THE NUMBER OF PLAYERS !";TEXT_SELECT_COLOR="SELECT A COLOR ";TEXT_TUTORIAL1="WELCOME TO FOUR COLORS! MATCH CARDS BY COLOR OR NUMBER AND BE THE FIRST TO GET RID OF THEM!";TEXT_TUTORIAL2="ACTION CARDS WILL MIX THE GAME UP!\n\nDRAW TWO FORCES THE NEXT PLAYER TO PICK TWO CARDS AND FORFEIT THE TURN";TEXT_TUTORIAL3="SKIP CARD STOPS THE NEXT PLAYER";
TEXT_TUTORIAL4="REVERSE CARD SWITCHES THE GAME WISE";TEXT_TUTORIAL5="THE WILD CARD CAN BE PLACED ON ANY CARD AT ANY TIME AND ALLOWS YOU TO CHANGE THE COLOR TO PLAY ";TEXT_TUTORIAL6="THE WILD DRAW FOUR IS A SPECIAL WILD THAT ALLOWS YOU TO CHANGE THE COLOR AND FORCES THE NEXT PLAYER TO PICK 4 CARDS. TO USE THIS CARD YOU MUST HAVE NO OTHER ALTERNATIVE CARDS TO PLAY";TEXT_TUTORIAL7="DO NOT FORGET TO PRESS THE 1 BUTTON WHEN YOU'LL HAVE ONLY ONE CARD LEFT OR YOU'LL PICK 2 PENALTY CARDS!";
TEXT_PLAYER_1="PLAYER 1";TEXT_PLAYER_2="PLAYER 2";TEXT_PLAYER_3="PLAYER 3";TEXT_PLAYER_4="PLAYER 4";TEXT_ALERT_1="YOU MUST PRESS ' 1 ' BUTTON WHEN YOU HAVE JUST ONE CARD. TWO CARDS PENALITY";TEXT_SHARE_IMAGE="200x200.jpg";TEXT_SHARE_TITLE="Congratulations!";TEXT_SHARE_MSG1="You collected <strong>";TEXT_SHARE_MSG2=" points</strong>!<br><br>Share your score with your friends!";TEXT_SHARE_SHARE1="My score is ";TEXT_SHARE_SHARE2=" points! Can you do better";
function CPreloader(){var a,c,b,d,g,h,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(h).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(k);d.x=CANVAS_WIDTH/2-k.width/2;d.y=CANVAS_HEIGHT-170;e.addChild(d);a=k.width;c=k.height;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);e.addChild(g);d.mask=
g;b=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";e.addChild(b);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;e.addChild(h)};this.refreshLoader=function(k){b.text=k+"%";g.graphics.clear();k=Math.floor(k*a/100);g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,k,c)};this._init()}
function CMain(a){var c,b=0,d=0,g=STATE_LOADING,h,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!0;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(FPS),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();c=!0};this.soundLoaded=function(){b++;h.refreshLoader(Math.floor(b/d*100));if(b===d)this.onRemovePreloader()};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});a.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});
a.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});a.push({path:"./sounds/",filename:"card_dealing",loop:!1,volume:1,ingamename:"card_dealing"});a.push({path:"./sounds/",filename:"snap",loop:!1,volume:1,ingamename:"snap"});a.push({path:"./sounds/",filename:"card",loop:!1,volume:1,ingamename:"card"});a.push({path:"./sounds/",filename:"special_card",loop:!1,volume:1,ingamename:"special_card"});a.push({path:"./sounds/",filename:"change_color",loop:!1,volume:1,ingamename:"change_color"});
d+=a.length;s_aSounds=[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+a[b].filename+".mp3",a[b].path+a[b].filename+".ogg"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("credits_panel",
"./sprites/credits_panel.png");s_oSpriteLibrary.addSprite("select_color_panel","./sprites/select_color_panel.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_yes_big","./sprites/but_yes_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");
s_oSpriteLibrary.addSprite("but_uno","./sprites/but_uno.png");s_oSpriteLibrary.addSprite("but_p2","./sprites/but_p2.png");s_oSpriteLibrary.addSprite("but_p3","./sprites/but_p3.png");s_oSpriteLibrary.addSprite("but_p4","./sprites/but_p4.png");s_oSpriteLibrary.addSprite("but_red","./sprites/_oButRed.png");s_oSpriteLibrary.addSprite("but_green","./sprites/_oButGreen.png");s_oSpriteLibrary.addSprite("but_blue","./sprites/_oButBlue.png");s_oSpriteLibrary.addSprite("but_yellow","./sprites/_oButYellow.png");
s_oSpriteLibrary.addSprite("stop_turn","./sprites/stop_turn.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_select_players","./sprites/bg_select_players.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("but_arrow",
"./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");s_oSpriteLibrary.addSprite("line_player","./sprites/line_players.png");s_oSpriteLibrary.addSprite("cards","./sprites/cards.png");s_oSpriteLibrary.addSprite("colors","./sprites/colors.png");s_oSpriteLibrary.addSprite("draw_four_anim","./sprites/draw_4.png");s_oSpriteLibrary.addSprite("draw_two_anim","./sprites/draw_2.png");s_oSpriteLibrary.addSprite("stop_turn_anim","./sprites/stop_turn.png");s_oSpriteLibrary.addSprite("clock_wise_anim",
"./sprites/change_clockwise.png");s_oSpriteLibrary.addSprite("change_color","./sprites/change_color.png");s_oSpriteLibrary.addSprite("cloud_uno","./sprites/cloud.png");s_oSpriteLibrary.addSprite("finger","./sprites/finger.png");s_oSpriteLibrary.addSprite("shuffle_anim","./sprites/shuffle_anim.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;h.refreshLoader(Math.floor(b/d*100));if(b===d)this.onRemovePreloader()};this._onAllImagesLoaded=function(){};
this.onRemovePreloader=function(){h.unload();isIOS()||(s_oSoundtrack=playSound("soundtrack",1,!0));this.gotoMenu()};this.gotoMenu=function(){new CMenu;g=STATE_MENU};this.gotoSelectPlayers=function(){new CSelectPlayers;g=STATE_SELECT_PLAYERS};this.gotoGame=function(a){s_bFirstGame=!1===a?!1:!0;e=new CGame(k);g=STATE_GAME};this.gotoHelp=function(){new CHelp;g=STATE_HELP};this.stopUpdate=function(){c=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);g===STATE_GAME&&e.update();s_oStage.update(a)}};s_oMain=
this;var k=a;ENABLE_CHECK_ORIENTATION=a.check_orientation;ENABLE_FULLSCREEN=a.fullscreen;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bFullscreen=!1,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_bFirstGame=!1,s_aSounds;
function CTextButton(a,c,b,d,g,h,e){var k,f,l,n,m;this._init=function(a,b,d,c,e,h,g){k=[];f=[];var u=createBitmap(d),p=Math.ceil(g/20);m=new createjs.Text(c," "+g+"px "+e,"#000000");m.textAlign="center";m.textBaseline="alphabetic";var q=m.getBounds();m.x=d.width/2+p;m.y=Math.floor(d.height/2)+q.height/3+p;n=new createjs.Text(c," "+g+"px "+e,h);n.textAlign="center";n.textBaseline="alphabetic";q=n.getBounds();n.x=d.width/2;n.y=Math.floor(d.height/2)+q.height/3;l=new createjs.Container;l.x=a;l.y=b;l.regX=
d.width/2;l.regY=d.height/2;l.addChild(u,m,n);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){k[a]=b;f[a]=d};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setTextPosition=function(a){n.y=a;m.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,c,b,d,g,h,e);return this}
function CToggle(a,c,b,d,g){var h,e,k,f;this._init=function(a,b,d,c,g){e=[];k=[];var l=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});h=c;f=createSprite(l,"state_"+h,d.width/2/2,d.height/2,d.width/2,d.height);f.x=a;f.y=b;f.stop();g.addChild(f);this._initListener()};this.unload=function(){s_bMobile?f.off("mousedown",this.buttonDown):(f.off("mousedown",this.buttonDown),f.off("mouseover",this.buttonOver));
f.off("pressup",this.buttonRelease);g.removeChild(f)};this._initListener=function(){if(s_bMobile)f.on("mousedown",this.buttonDown);else f.on("mousedown",this.buttonDown),f.on("mouseover",this.buttonOver);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){e[a]=b;k[a]=d};this.setActive=function(a){h=a;f.gotoAndStop("state_"+h)};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;playSound("click",1,!1);h=!h;f.gotoAndStop("state_"+h);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(k[ON_MOUSE_UP],
h)};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.buttonOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.setPosition=function(a,b){f.x=a;f.y=b};this._init(a,c,b,d,g)}
function CGfxButton(a,c,b,d){var g,h,e,k,f;this._init=function(a,b,d,c){g=!1;h=1;e=[];k=[];f=createBitmap(d);f.x=a;f.y=b;f.scaleX=f.scaleY=h;f.regX=d.width/2;f.regY=d.height/2;c.addChild(f);this._initListener()};this.unload=function(){s_bMobile?f.off("mousedown",this.buttonDown):(f.off("mousedown",this.buttonDown),f.off("mouseover",this.buttonOver));f.off("pressup",this.buttonRelease);d.removeChild(f)};this.setVisible=function(a){f.visible=a};this.setClickable=function(a){g=!a};this._initListener=
function(){if(s_bMobile)f.on("mousedown",this.buttonDown);else f.on("mousedown",this.buttonDown),f.on("mouseover",this.buttonOver);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){e[a]=b;k[a]=d};this.buttonRelease=function(){g||(f.scaleX=h,f.scaleY=h,e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(k[ON_MOUSE_UP]))};this.buttonDown=function(){g||(f.scaleX=.9*h,f.scaleY=.9*h,playSound("click",1,!1),e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN]))};this.buttonOver=function(a){s_bMobile||
g||(a.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(f).to({scaleX:.9*h,scaleY:.9*h},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:h},650,createjs.Ease.quadIn).call(function(){l.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(f).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){l.trebleAnimation()})};this.setPosition=function(a,b){f.x=a;f.y=b};
this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};var l=this;this._init(a,c,b,d);return this}
function CPanelTutorial(){var a,c,b,d,g,h,e;this.init=function(){s_oInterface.setButtonUno(!1);e=new createjs.Container;h=0;a=new createjs.Container;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;c=new createBitmap(s_oSpriteLibrary.getSprite("msg_box"));c.regX=398;c.regY=258.5;c.alpha=.8;a.addChild(c);s_oStage.addChild(a);b=new CGfxButton(a.getBounds().width/2-50,0,s_oSpriteLibrary.getSprite("but_arrow"),a);b.addEventListener(ON_MOUSE_DOWN,this.onButNext,this);var k=s_oSpriteLibrary.getSprite("but_arrow");
d=new CGfxButton(-(a.getBounds().width/2-50),0,k,a);d.addEventListener(ON_MOUSE_DOWN,this.onButBack,this);d.getButtonImage().rotation=180;g=new CGfxButton(a.getBounds().width/2-53,a.getBounds().height/2-53,s_oSpriteLibrary.getSprite("but_skip"),a);g.addEventListener(ON_MOUSE_DOWN,this.onButSkip,this);this.loadPage(h)};this.loadPage=function(c){switch(c){case 0:d.setVisible(!1);c=new createjs.Text(TEXT_TUTORIAL1," 30px "+PRIMARY_FONT,"#FFFFFF");c.lineWidth=320;c.x=-60;c.y=-95;c.align="center";var f=
new CCard(-215,0,e,"card_1_7",0,0);e.addChild(c);f.setAnimTutorial("tutorial");a.addChild(e);break;case 1:d.setVisible(!0);c=new createjs.Text(TEXT_TUTORIAL2," 30px "+PRIMARY_FONT,"#FFFFFF");c.lineWidth=320;c.x=-60;c.y=-130;c.align="center";f=new CCard(-215,0,e,"card_0_12",0,0);e.addChild(c);f.setAnimTutorial("draw2tutorial");break;case 2:c=new createjs.Text(TEXT_TUTORIAL3," 30px "+PRIMARY_FONT,"#FFFFFF");c.lineWidth=320;c.x=-60;c.y=-45;c.align="center";f=new CCard(-215,0,e,"card_1_7",0,0);e.addChild(c);
f.setAnimTutorial("stopTurnTutorial");break;case 3:c=new createjs.Text(TEXT_TUTORIAL4," 30px "+PRIMARY_FONT,"#FFFFFF");c.lineWidth=320;c.x=-60;c.y=-55;c.align="center";f=new CCard(-215,0,e,"card_1_7",0,0);e.addChild(c);f.setAnimTutorial("changeClockWiseTutorial");break;case 4:c=new createjs.Text(TEXT_TUTORIAL5," 30px "+PRIMARY_FONT,"#FFFFFF");c.lineWidth=320;c.x=-60;c.y=-95;c.align="center";f=new CCard(-215,0,e,"color",0,0);e.addChild(c);f.instantShow();break;case 5:b.setVisible(!0);c=new createjs.Text(TEXT_TUTORIAL6,
" 30px "+PRIMARY_FONT,"#FFFFFF");c.lineWidth=320;c.x=-60;c.y=-170;c.align="center";f=new CCard(-215,0,e,"draw_four",0,0);e.addChild(c);f.instantShow();break;case 6:b.setVisible(!1),c=new createjs.Text(TEXT_TUTORIAL7," 30px "+PRIMARY_FONT,"#FFFFFF"),c.lineWidth=320,c.x=-60,c.y=-100,c.align="center",f=new createBitmap(s_oSpriteLibrary.getSprite("but_uno")),f.regX=50,f.regY=50.5,f.x=-215,f.scaleX=1.5,f.scaleY=1.5,e.addChild(c),e.addChild(f)}};this.onButNext=function(){h++;e.removeAllChildren();this.loadPage(h)};
this.onButBack=function(){h--;e.removeAllChildren();this.loadPage(h)};this.onButSkip=function(){s_oStage.removeChild(a);s_oInterface.setButtonUno(!0);s_oGame.startGame()};this.init()}
function CTurnManager(){var a,c=0,b=0;this.init=function(){a=!0;b=0;c=3===b?0:b+1;s_oTurnManager=this};this.changeClockWise=function(){a=!0===a?!1:!0};this.nextTurn=function(){!0===a?b===NUM_PLAYERS-1?(b=0,c=1):(b++,c=b===NUM_PLAYERS-1?0:b+1):0===b?(b=NUM_PLAYERS-1,c=NUM_PLAYERS-2):(b--,c=0===b?NUM_PLAYERS-1:b-1)};this.checkTurn=function(){return b};this.prevTurn=function(){!0===a?0===b?(b=NUM_PLAYERS-1,c=NUM_PLAYERS-2):(b--,c=0===b?NUM_PLAYERS-1:b-1):b===NUM_PLAYERS-1?(b=0,c=1):(b++,c=b===NUM_PLAYERS-
1?0:b+1)};this.checkPrevTurn=function(){return!0===a?0===b?NUM_PLAYERS-1:b-1:b===NUM_PLAYERS-1?0:b+1};this.checkNextPlayer=function(){return c};this.setTurn=function(d){b=d;c=!0===a?b===NUM_PLAYERS-1?0:b+1:0===b?NUM_PLAYERS-1:b-1};this.getClockWise=function(){return a};this.init()}s_oTurnManager=null;
function CListernableObject(){var a;this._init=function(){a=[]};this.addEventListener=function(c,b,d){a[c]={cb:b,owner:d}};this.removeEventListener=function(c){a[c]=null};this.callEvent=function(c,b){a[c]&&(b?a[c].cb.apply(a[c].owner,[b]):a[c].cb.call(a[c].owner))};this._init()}
function CAnimation(){var a,c,b,d,g,h,e,k;this.init=function(){e=!1;var f=s_oSpriteLibrary.getSprite("draw_four_anim"),f={images:[f],frames:{width:292,height:290,regX:146,regY:145},animations:{anim:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13],next:"stop",speed:.8},reverse:{frames:[13,12,11,10,9,8,7,6,5,4,3,2,1,0],next:[0],speed:.8},stop:[13]}},f=new createjs.SpriteSheet(f);a=new createjs.Sprite(f,0);f=s_oSpriteLibrary.getSprite("draw_two_anim");f={images:[f],frames:{width:292,height:322,regX:146,regY:161},
animations:{anim:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13],next:"stop",speed:.8},reverse:{frames:[13,12,11,10,9,8,7,6,5,4,3,2,1,0],next:[0],speed:.8},stop:[13]}};f=new createjs.SpriteSheet(f);c=new createjs.Sprite(f,0);f=s_oSpriteLibrary.getSprite("stop_turn_anim");b=new createBitmap(f,292,300);f=s_oSpriteLibrary.getSprite("clock_wise_anim");d=new createBitmap(f,292,300);f=s_oSpriteLibrary.getSprite("change_color");f={images:[f],frames:{width:328,height:315,regX:164,regY:157.5},animations:{anim:{frames:[0,
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],next:"anim",speed:.8},stop:[16],color_0:{frames:[0,1,2,3,4,5,6],speed:.8},color_1:{frames:[0,1,2],speed:.8},color_2:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],speed:.8},color_3:{frames:[0,1,2,3,4,5,6,7,8,9,10],speed:.8}}};f=new createjs.SpriteSheet(f);g=new createjs.Sprite(f,0);f=s_oSpriteLibrary.getSprite("shuffle_anim");f={images:[f],frames:{width:403,height:386,regX:201.5,regY:193},animations:{anim:{frames:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],
next:"anim"},idle:[17]}};f=new createjs.SpriteSheet(f);k=new createjs.Sprite(f,"idle")};this.drawFourAnim=function(){a.alpha=0;a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2;a.scaleX=.01;a.scaleY=.01;s_oStage.addChild(a);a.stop();playSound("special_card",.5,!1);(new createjs.Tween.get(a)).to({alpha:1,scaleX:1.4,scaleY:1.4},200,createjs.Ease.cubicOut).wait(200).call(function(){a.gotoAndPlay("anim")}).wait(1E3).call(function(){a.gotoAndPlay("reverse")}).wait(200).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(a);
s_oGame.onEndDrawFour()})};this.drawTwoAnim=function(){c.alpha=0;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.scaleX=.01;c.scaleY=.01;s_oStage.addChild(c);c.stop();playSound("special_card",.5,!1);(new createjs.Tween.get(c)).to({alpha:1,scaleX:1.4,scaleY:1.4},200,createjs.Ease.cubicOut).wait(200).call(function(){c.gotoAndPlay("anim");setVolume("special_card",.2)}).wait(1E3).call(function(){c.gotoAndPlay("reverse");setVolume("special_card",.1)}).wait(200).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(c);
s_oGame.onEndDrawTwo()})};this.stopTurn=function(){b.alpha=0;b.regX=146;b.regY=150;b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2;b.scaleX=.01;b.scaleY=.01;s_oStage.addChild(b);playSound("game_over",1,!1);(new createjs.Tween.get(b)).to({alpha:1,scaleX:2,scaleY:2},200,createjs.Ease.cubicOut).to({scaleX:1.6,scaleY:1.6},200).to({scaleX:2,scaleY:2},200).to({scaleX:1.6,scaleY:1.6},200).to({scaleX:2,scaleY:2},200).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(b);
s_oGame.onNextTurn()})};this.changeClockWise=function(a){d.alpha=0;d.rotation=0;d.regX=146;d.regY=150;d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2;d.scaleX=.01;d.scaleY=.01;s_oStage.addChild(d);playSound("special_card",.5,!1);!1===a?(new createjs.Tween.get(d)).to({alpha:1,scaleX:2,scaleY:2},200,createjs.Ease.cubicOut).to({rotation:360},500).wait(500).to({rotation:-360},500).wait(500).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(d);s_oGame.onNextTurn()}):
(new createjs.Tween.get(d)).to({alpha:1,scaleX:2,scaleY:2},200,createjs.Ease.cubicOut).to({rotation:-360},500).wait(500).to({rotation:360},500).wait(500).to({alpha:0,scaleX:.01,scaleY:.01},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(d);s_oGame.onNextTurn()})};this.changeColor=function(a){h=a;g.alpha=0;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2;g.scaleX=.01;g.scaleY=.01;s_oStage.addChild(g);g.stop();playSound("change_color",.5,!1);(new createjs.Tween.get(g)).to({alpha:1,scaleX:1.4,
scaleY:1.4},200,createjs.Ease.cubicOut).call(function(){g.gotoAndPlay("anim")}).wait(1300).call(function(){g.gotoAndStop(16);g.gotoAndPlay("color_"+a);e=!0;g.on("animationend",s_oCAnimation.endAnimation)})};this.endAnimation=function(){!0===e&&(stopSound("change_color"),playSound("special_card",1,!1),e=!1,g.off("animationend",s_oCAnimation.endAnimation),g.stop(),(new createjs.Tween.get(g)).to({scaleX:2,scaleY:2},250).to({scaleX:1.4,scaleY:1.4},250).to({scaleX:2,scaleY:2},250).to({scaleX:1.4,scaleY:1.4},
250).to({alpha:0,scaleX:.1,scaleY:.1},200,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(g);g.gotoAndStop(0);s_oInterface.refreshColor(h);s_oGame.onNextTurn()}))};this.shuffleAnimation=function(a,b,c,d){k.alpha=0;k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2;k.scaleX=.01;k.scaleY=.01;s_oStage.addChild(k);k.stop();(new createjs.Tween.get(k)).to({alpha:1,scaleX:1.6,scaleY:1.6},400,createjs.Ease.cubicOut).call(function(){k.gotoAndPlay("anim");playSound("card_dealing",1,!0)}).wait(1700).call(function(){k.gotoAndStop("idle");
stopSound("change_color")}).to({alpha:0,scaleX:.01,scaleY:.01},300,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(k);s_oGame.onEndShuffle(a,b,c,d)})};this.init();s_oCAnimation=this}s_oCAnimation=null;
function CMenu(){var a,c,b,d,g,h,e,k,f,l,n,m,p=null,t=null;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(e);var q=s_oSpriteLibrary.getSprite("but_play");k=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,q,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);q=s_oSpriteLibrary.getSprite("but_info");g=q.height/2+20+q.width;h=q.height/2+10;n=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-240,q,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onCreditsBut,
this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-q.height/2-10,d=q.height/2+10,l=new CToggle(b,d,q,s_bAudioActive,s_oStage),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=window.document;var r=q.documentElement;p=r.requestFullscreen||r.mozRequestFullScreen||r.webkitRequestFullScreen||r.msRequestFullscreen;t=q.exitFullscreen||q.mozCancelFullScreen||q.webkitExitFullscreen||q.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(p=!1);p&&!inIframe()&&
(q=s_oSpriteLibrary.getSprite("but_fullscreen"),a=q.width/4+10,c=q.height/2+10,m=new CToggle(a,c,q,s_bFullscreen,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){f.visible=!1});null!==s_oSoundtrack&&setVolume("soundtrack",1);this.refreshButtonPos()};this.unload=function(){k.unload();k=null;f.visible=!1;n.unload();
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;p&&!inIframe()&&m.unload();s_oStage.removeAllChildren();s_oMenu=null};this.refreshButtonPos=function(){n.setPosition(g+s_iOffsetX,s_iOffsetY+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(b-s_iOffsetX,s_iOffsetY+d);p&&!inIframe()&&m.setPosition(a+s_iOffsetX,c+s_iOffsetY)};this.resetFullscreenBut=function(){m.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?t.call(window.document):p.call(window.document.documentElement);
sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){this.unload();isIOS()&&null===s_oSoundtrack&&(s_oSoundtrack=playSound("soundtrack",1,!0));$(s_oMain).trigger("start_session");s_oMain.gotoSelectPlayers()};s_oMenu=this;this._init()}var s_oMenu=null;
function CSelectPlayers(){var a,c,b,d,g,h,e,k,f=null,l=null,n;this._init=function(){var m=createBitmap(s_oSpriteLibrary.getSprite("bg_select_players"));s_oStage.addChild(m);m=s_oSpriteLibrary.getSprite("but_p2");g=new CGfxButton(CANVAS_WIDTH/2-450,CANVAS_HEIGHT-500,m,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onButP2,this);m=s_oSpriteLibrary.getSprite("but_p3");h=new CGfxButton(CANVAS_WIDTH/2+10,CANVAS_HEIGHT-500,m,s_oStage);h.addEventListener(ON_MOUSE_UP,this._onButP3,this);m=s_oSpriteLibrary.getSprite("but_p4");
e=new CGfxButton(CANVAS_WIDTH/2+450,CANVAS_HEIGHT-500,m,s_oStage);e.addEventListener(ON_MOUSE_UP,this._onButP4,this);m=new createjs.Text(TEXT_SELECT_PLAYERS," 55px "+PRIMARY_FONT,"#FFF");m.textAlign="center";m.x=CANVAS_WIDTH/2;m.y=300;m.textBaseline="alphabetic";s_oStage.addChild(m);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),b=CANVAS_WIDTH-m.height/2-10,d=m.height/2+10,n=new CToggle(b,d,m,s_bAudioActive,s_oStage),n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);m=window.document;var p=m.documentElement;f=p.requestFullscreen||p.mozRequestFullScreen||p.webkitRequestFullScreen||p.msRequestFullscreen;l=m.exitFullscreen||m.mozCancelFullScreen||m.webkitExitFullscreen||m.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(f=!1);f&&!inIframe()&&(m=s_oSpriteLibrary.getSprite("but_fullscreen"),a=m.width/4+10,c=m.height/2+10,k=new CToggle(a,c,m,s_bFullscreen,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));this.refreshButtonPos()};this._onButP2=function(){NUM_PLAYERS=
2;this.unload();$(s_oMain).trigger("select_players",2);s_oMain.gotoGame()};this._onButP3=function(){NUM_PLAYERS=3;this.unload();$(s_oMain).trigger("select_players",3);s_oMain.gotoGame()};this._onButP4=function(){NUM_PLAYERS=4;this.unload();$(s_oMain).trigger("select_players",4);s_oMain.gotoGame()};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n.unload(),n=null;f&&!inIframe()&&k.unload();g.unload();h.unload();e.unload();s_oStage.removeAllChildren();s_oSelectPlayers=null};this.refreshButtonPos=
function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(b-s_iOffsetX,s_iOffsetY+d);f&&!inIframe()&&k.setPosition(a+s_iOffsetX,c+s_iOffsetY)};this.resetFullscreenBut=function(){k.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?l.call(window.document):f.call(window.document.documentElement);sizeHandler()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oSelectPlayers=this;this._init()}var s_oSelectPlayers=null;
function CCard(a,c,b,d,g,h){var e=!1,k,f,l,n,m,p,t,q,r,x;this._init=function(a,b,c,d,e,h,g){x=c;l=d;n=e;m=h;k=!1;f=0===m||2===m?"red":"black";r=new createjs.Container;r.x=a;r.y=b;x.addChild(r);a={images:[s_oSpriteLibrary.getSprite("cards")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_0_0:[0],card_0_1:[1],card_0_2:[2],card_0_3:[3],card_0_4:[4],card_0_5:[5],card_0_6:[6],card_0_7:[7],card_0_8:[8],card_0_9:[9],card_0_10:[10],card_0_11:[11],card_0_12:[12],
card_1_0:[13],card_1_1:[14],card_1_2:[15],card_1_3:[16],card_1_4:[17],card_1_5:[18],card_1_6:[19],card_1_7:[20],card_1_8:[21],card_1_9:[22],card_1_10:[23],card_1_11:[24],card_1_12:[25],card_2_0:[26],card_2_1:[27],card_2_2:[28],card_2_3:[29],card_2_4:[30],card_2_5:[31],card_2_6:[32],card_2_7:[33],card_2_8:[34],card_2_9:[35],card_2_10:[36],card_2_11:[37],card_2_12:[38],card_3_0:[39],card_3_1:[40],card_3_2:[41],card_3_3:[42],card_3_4:[43],card_3_5:[44],card_3_6:[45],card_3_7:[46],card_3_8:[47],card_3_9:[48],
card_3_10:[49],card_3_11:[50],card_3_12:[51],color:[52],draw_four:[53],back:[54],tutorial:{frames:[20,5,47,31],speed:.1},draw2tutorial:{frames:[12,25,38,51],speed:.1},stopTurnTutorial:{frames:[10,23,36,49],speed:.1},changeClockWiseTutorial:{frames:[11,24,37,50],speed:.1}}};a=new createjs.SpriteSheet(a);q=createSprite(a,"back",CARD_WIDTH/2,CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);q.stop();r.addChild(q);q.on("mousedown",this._mouseDown);p=[];t=[]};this.getCardSprite=function(){return q};this.setAnimTutorial=
function(a){q.gotoAndPlay(a)};this.unload=function(){q.off("mousedown",this._mouseDown);x.removeChild(r)};this.unloadEvent=function(){q.off("mousedown",this._mouseDown)};this.saveInfo=function(){return{szFotogram:l,iRank:n,iSuit:m,bValue:!0}};this.changeInfo=function(a,b,c){l=a;n=b;m=c};this.instantShow=function(){q.gotoAndStop(l)};this.setValue=function(a){q.gotoAndStop(l);playSound("card",1,!1);createjs.Tween.get(r).to({scaleX:1},200).call(function(){})};this.setActive=function(a){a?r.addChild(void 0):
r.removeChild(void 0)};this.setVisible=function(a){r.visible=!0===a?!0:!1};this.onSetTurned=function(){k=!0};this.offSetTurned=function(){k=!1};this.moveCard=function(a,b,c,d){var f=this;createjs.Tween.get(r).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){s_oGame.playedCard(f)})};this.moveCardFirstHand=function(a,b,c,d){var f=this;createjs.Tween.get(r).wait(d).to({x:a,y:b},c,createjs.Ease.cubicOut).call(function(){playSound("card_dealing",1,!1);s_oGame.onCardDealed(f)})};this.moveFirstLastCard=
function(a,b,c,d){var f=this;createjs.Tween.get(r).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){s_oGame.onFirstLastCardDealed(f)})};this.setOnTop=function(){x.addChildAt(r,x.numChildren)};this.moveToSuit=function(a,b,c){createjs.Tween.get(r).wait(c).to({x:a,y:b},200,createjs.Ease.cubicOut).call(function(){s_oGame.stackInSuit(w)})};this.setPlaced=function(){e=!0;w.showCard()};this.stackInPlace=function(a,b,c){createjs.Tween.get(r).to({x:a,y:b},c,createjs.Ease.cubicOut).call(function(){k=
!0})};this.stackAndDeactive=function(a,b,c){createjs.Tween.get(r).to({x:a,y:b},c,createjs.Ease.cubicOut)};this._mouseDown=function(a){!1!==k&&s_oGame.pickCard(w,a)};this.getPlaced=function(){return e};this.showCard=function(a,b){var c=this;createjs.Tween.get(r).wait(a).to({scaleX:.1},200).call(function(){c.setValue(b)}).call(function(){k=!0})};this.showCardNoInput=function(a,b){var c=this;createjs.Tween.get(r).wait(a).to({scaleX:.1},200).call(function(){c.setValue(b)}).call(function(){k=!1})};this.hideCard=
function(){var a=this;createjs.Tween.get(r).to({scaleX:.1},200).call(function(){a.setBack()})};this.setPos=function(a,b){r.x=a;r.y=b};this.setBack=function(){k=!1;q.gotoAndStop("back");var a=this;createjs.Tween.get(r).to({scaleX:1},200).call(function(){a.cardHidden()})};this.cardHidden=function(){p[ON_CARD_HIDE]&&p[ON_CARD_HIDE].call(t[ON_CARD_HIDE],this)};this.getRank=function(){return n};this.getSuit=function(){return m};this.getColor=function(){return f};this.getFotogram=function(){return l};this.getPos=
function(){return{x:r.x,y:r.y}};this.getSprite=function(){return r};this.getLogicRect=function(){return new createjs.Rectangle(r.x-CARD_WIDTH/2,r.y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT)};this.getTurned=function(){return k};var w=this;this._init(a,c,b,d,g,h);this.getGlobalToLocal=function(a,b){return q.globalToLocal(a/s_oStage.scaleX,b/s_oStage.scaleY)}}
function CDeckDisplayer(a,c,b){var d,g,h,e;this._init=function(){d=[];g=new createjs.Container;h=!1;g.x=a;g.y=c;e=b;e.addChild(g,e);g.on("mousedown",this.onDraw,this)};this.initializeDeck=function(){for(var a,b=0;4>b;b++)for(var c=0;10>c;c++)a=c,d.push(new CCard(0,0,g,"card_"+b+"_"+c,a,b));for(b=0;4>b;b++)for(c=0;9>c;c++)a=c+1,d.push(new CCard(0,0,g,"card_"+b+"_"+a,a,b));for(b=0;4>b;b++)for(c=0;2>c;c++)d.push(new CCard(0,0,g,"card_"+b+"_10",10,b)),d.push(new CCard(0,0,g,"card_"+b+"_11",11,b)),d.push(new CCard(0,
0,g,"card_"+b+"_12",12,b));for(b=0;4>b;b++)d.push(new CCard(0,0,g,"color",13,4)),d.push(new CCard(0,0,g,"draw_four",14,4))};this.shuffle=function(){var a;for(a=d.length;a;a--){var b=Math.floor(Math.random()*a);var c=d[a-1];d[a-1]=d[b];d[b]=c}};this.moveContainer=function(a,b,c,d){createjs.Tween.get(g).wait(d).to({x:a,y:b},c,createjs.Ease.linear)};this.takeFirstLastCard=function(){for(;4===d[d.length-1].getSuit();)this.shuffle();return d.pop()};this.takeLastCard=function(){return d.pop()};this.getLastCard=
function(){return d[d.length-1]};this.getCardByIndex=function(a){return d[a]};this.removeCardByIndex=function(a){return d.splice(a,1)};this.pushCard=function(a){d.push(a)};this.getContainer=function(){return g};this.getLength=function(){return d.length};this.onDraw=function(){if(!1===h)s_oGame.onDraw()};this.disableInputUsedCards=function(){d[d.length-1].offSetTurned()};this.disableInputDraw=function(){h=!0};this.enableInputDraw=function(){h=!1};this.getIndexChild=function(){return s_oStage.getChildIndex(g)};
this.setChildDepth=function(a){s_oStage.addChildAt(g,a)};this.getGlobalPosition=function(){return{x:g.x,y:g.y}};this.setOnTop=function(){e.addChildAt(g,e.numChildren)};this.addNewCardUnderTheDeck=function(a){for(var b=0;b<a.length;b++)d.push(a[b])};this.removeAllCardUnderTheDeck=function(){for(var a=[],b=0;b<d.length-1;b++)a.push(d.shift());return a};this._init()}
function CHandDisplayer(a,c,b,d,g,h,e){var k,f,l,n,m,p,t,q,r=!1;this.init=function(){k=a;f=c;l=[];n=new createjs.Container;n.x=b;n.y=d;q=h;q.addChild(n);var g=s_oSpriteLibrary.getSprite("line_player"),g={images:[g],frames:{width:524,height:18,regX:262,regY:9},animations:{off:[0],on:[1],idle:{frames:[0,1],speed:.1}}},g=new createjs.SpriteSheet(g);m=new createjs.Sprite(g,"off");m.stop();p=new createjs.Text(e," 34px "+PRIMARY_FONT,"#FFFFFF");0!==k?(m.x=CANVAS_WIDTH/2,d>CANVAS_HEIGHT/2?(p.x=CANVAS_WIDTH/
2+40,m.y=d-135,p.y=d-178):(p.x=CANVAS_WIDTH/2-195,m.y=d+135,p.y=d+140)):(m.y=CANVAS_HEIGHT/2,b<CANVAS_WIDTH/2?(m.x=b+100,m.rotation=90,p.x=b+150,p.y=d+70,p.rotation=90):(m.x=b-100,m.rotation=-90,p.x=b-150,p.y=d+6,p.rotation=-90));s_oStage.addChild(m);s_oStage.addChild(p);g=s_oSpriteLibrary.getSprite("cloud_uno");g={images:[g],frames:{width:261,height:194,regX:130.5,regY:97},animations:{cloud1:[0],cloud2:[1]}};g=new createjs.SpriteSheet(g);t=new createjs.Sprite(g,"cloud1");t.alpha=0;t.scaleX=.1;t.scaleY=
.1};this.getGlobalPosition=function(){for(var a=0,b=0,c=0;c<l.length;c++)0!==k?a+=CARD_WIDTH/2:b+=CARD_HEIGHT/2;return{x:n.x+a,y:n.y+b}};this.getContainerPos=function(){return{x:n.x,y:n.y}};this.getCardPositionByIndex=function(a){a=l[a].getPos();return{x:a.x,y:a.y}};this.searchIndexCard=function(a){for(var b=0;b<l.length;b++)if(a===l[b])return b};this.removeCardByIndex=function(a){return l.splice(a,1)};this.getPosNewCard=function(){return{x:l.length*k,y:l.length*f}};this.pushCard=function(a){l.push(a);
if(0===f&&d>CANVAS_HEIGHT/2)l[l.length-1].getCardSprite().on("mouseover",this.onMouseOver)};this.getContainer=function(){return n};this.getLastCard=function(){return l[l.length-1]};this.getLength=function(){return l.length};this.centerContainer=function(){var a=n.getBounds();0!==k?createjs.Tween.get(n).to({x:CANVAS_WIDTH/2-a.width/2+CARD_WIDTH/2},300,createjs.Ease.linear):createjs.Tween.get(n).to({y:CANVAS_HEIGHT/2-a.height/2+CARD_HEIGHT/1.5-40},300,createjs.Ease.linear)};this.setOnTop=function(){q.addChildAt(n,
q.numChildren)};this.setChildDepth=function(a){a>n.s_oStage.numChild-1&&(a=n.s_oStage.numChild-1);s_oStage.addChildAt(a)};this.getContainerInfo=function(){return n.getBounds()};this.getCardByIndex=function(a){return l[a]};this.organizeHand=function(a){var b=this;if(0!==k)for(var c=0;c<l.length;c++)a=k*c,createjs.Tween.get(l[c].getSprite()).to({x:a},300,createjs.Ease.linear).call(b.centerContainer);else for(c=0;c<l.length;c++)a=f*c,createjs.Tween.get(l[c].getSprite()).to({y:a},300,createjs.Ease.linear).call(function(){b.centerContainer()})};
this.setOnTurn=function(){p.alpha=1;r=!0;if(!1===createjs.Tween.hasActiveTweens(p)&&0===g)this.onTweenPlayer();m.gotoAndStop("on")};this.onTweenPlayer=function(){var a=this;!0===r?(new createjs.Tween.get(p)).to({alpha:.15},500).to({alpha:1},500).call(function(){a.onTweenPlayer()}):p.alpha=.15};this.setOffTurn=function(){createjs.Tween.removeTweens(p);r=!1;p.alpha=.15;m.gotoAndStop("off")};this.checkUno=function(){1===l.length&&(this.setOnTop(),0!==k?d<CANVAS_HEIGHT/2?(t.gotoAndStop("cloud2"),t.x=
CANVAS_WIDTH/2-270,t.y=CANVAS_HEIGHT/2-300):(t.gotoAndStop("cloud1"),t.x=CANVAS_WIDTH/2+300,t.y=CANVAS_HEIGHT/2+100):b<CANVAS_WIDTH/2?(t.gotoAndStop("cloud1"),t.x=CANVAS_WIDTH/2-350,t.y=CANVAS_HEIGHT/2-30):(t.gotoAndStop("cloud2"),t.x=CANVAS_WIDTH/2+350,t.y=CANVAS_HEIGHT/2-200),s_oStage.addChild(t),(new createjs.Tween.get(t)).to({alpha:1,scaleX:1,scaleY:1},300,createjs.Ease.bounceOut).wait(1500).to({scaleX:.1,scaleY:.1},300,createjs.Ease.cubicIn).to({alpha:0},20).call(function(){s_oStage.removeChild(t)}))};
this.onMouseOver=function(a){s_bMobile||(a.target.cursor="pointer")};this.init()}
function CGame(a){var c,b=0,d,g=null,h,e=[],k,f,l,n=!1,m,p,t,q,r,x,w,u,v,A,B,C,z;this._init=function(){c=1E5;C=-(STARTING_NUM_CARDS-1);q=x=A=!1;f=new CTurnManager;B=[];B[0]=TEXT_PLAYER_1;B[1]=TEXT_PLAYER_2;B[2]=TEXT_PLAYER_3;B[3]=TEXT_PLAYER_4;m=new CAnimation;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);d=new CInterface;!0===s_bFirstGame?new CPanelTutorial:this.startGame();setVolume("soundtrack",.4)};this.startGame=function(){v=new createjs.Container;var a={images:[s_oSpriteLibrary.getSprite("finger")],
frames:{width:202,height:277,regX:101,regY:138.5},animations:{idle:{frames:[0,1,2,3,4,5,6,7,8,9],speed:.9}}},a=new createjs.SpriteSheet(a);t=new createjs.Sprite(a,"idle");t.scaleX=.5;t.scaleY=.5;t.x=CANVAS_WIDTH/2-90;t.y=CANVAS_HEIGHT/2-100;u=new createjs.Container;for(a=0;a<NUM_PLAYERS;a++){var b=0,c=0;aHandPos["num_player_"+NUM_PLAYERS][a].x===CANVAS_WIDTH/2?b=CARD_WIDTH/2:c=CARD_HEIGHT/4;e[a]=new CHandDisplayer(b,c,aHandPos["num_player_"+NUM_PLAYERS][a].x,aHandPos["num_player_"+NUM_PLAYERS][a].y,
a,u,B[a])}w=new createjs.Container;h=new CDeckDisplayer(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,w);k=new CDeckDisplayer(CANVAS_WIDTH/2+CARD_WIDTH,CANVAS_HEIGHT/2,w);k.disableInputDraw();h.initializeDeck();h.shuffle();h.getContainer().on("mouseover",this.onMouseOverDeck);v.addChild(w);v.addChild(u);s_oStage.addChild(v);this.getFirstHand();z=new createjs.Text(TEXT_ALERT_1,"22px "+PRIMARY_FONT,"#FFFFFF");z.x=CANVAS_WIDTH/2+290;z.y=CANVAS_HEIGHT/2+20;z.textAlign="left";z.lineWidth=250;z.alpha=0;s_oStage.addChild(z)};
this.getFirstHand=function(){var a=h.takeLastCard(),b=f.checkTurn(),c=e[b].getContainerPos(),b=e[b].getPosNewCard(),d=h.getGlobalPosition();a.setOnTop();v.addChildAt(w,v.numChildren);h.setOnTop();a.moveCardFirstHand(c.x+b.x-d.x,c.y+b.y-d.y,250)};this.onCardDealed=function(a){var b=f.checkTurn();e[b].pushCard(new CCard(e[b].getPosNewCard().x,e[b].getPosNewCard().y,e[b].getContainer(),a.getFotogram(),a.getRank(),a.getSuit()));a.unload();a=e[b].getLastCard();e[b].centerContainer();0===b&&a.showCardNoInput(0,
"mute");f.nextTurn();e[e.length-1].getLength()<STARTING_NUM_CARDS?this.getFirstHand():(v.addChildAt(w,v),h.setOnTop(),a=h.takeFirstLastCard(),a.moveFirstLastCard(CARD_WIDTH,0,600),d.setOnTop())};this.onFirstLastCardDealed=function(a){k.pushCard(new CCard(0,0,k.getContainer(),a.getFotogram(),a.getRank(),a.getSuit()));a.unload();a=k.getLastCard();a.showCardNoInput();h.moveContainer(CANVAS_WIDTH/2-CARD_WIDTH/2,CANVAS_HEIGHT/2,400);k.moveContainer(CANVAS_WIDTH/2+CARD_WIDTH/2,CANVAS_HEIGHT/2,400);l=k.getLastCard().getSuit();
d.refreshColor(l);f.setTurn(Math.floor(Math.random()*NUM_PLAYERS)+0);var b=f.checkTurn();e[b].setOnTurn(b);k.disableInputUsedCards();this.applyEffectOnCard(a,!0)};this.pickCard=function(a,b){C++;var c=k.getLastCard(),d=f.checkTurn(),g=e[d].getContainerPos(),h=k.getGlobalPosition();v.addChildAt(u,v.numChildren);e[d].setOnTop();0===d&&(a.getRank()===c.getRank()&&"draw_four"!==a.getFotogram()||a.getSuit()===l||"color"===a.getFotogram()?(this.offInputPlayer(),a.moveCard(h.x-g.x,h.y-g.y,300),playSound("card",
1,!1),2===e[0].getLength()&&(n=!0)):14===a.getRank()&&!0===this.checkAvaiableDrawFour()&&(this.offInputPlayer(),a.moveCard(h.x-g.x,h.y-g.y,300),playSound("card",1,!1),2===e[0].getLength()&&(n=!0)))};this.cpuPickCard=function(a){var b=f.checkTurn(),c=e[b].getContainerPos(),d=k.getGlobalPosition();v.addChildAt(u,v.numChildren);e[b].setOnTop();a.moveCard(d.x-c.x,d.y-c.y,400,1E3);h.setChildDepth(2);k.setChildDepth(2);a.showCard(1E3)};this.playedCard=function(a){var b=f.checkTurn(),c=e[b].searchIndexCard(a);
k.pushCard(new CCard(0,0,k.getContainer(),a.getFotogram(),a.getRank(),a.getSuit()));k.disableInputUsedCards();k.getLastCard().instantShow();e[b].removeCardByIndex(c);a.unload();0!==b&&e[b].checkUno();4!==k.getLastCard().getSuit()&&(l=k.getLastCard().getSuit(),d.refreshColor(l));e[b].organizeHand(c);this.applyEffectOnCard(a)};this.applyEffectOnCard=function(a,b){var c=this;b||(b=!1);if(!0===b){p=f.checkTurn();f.prevTurn();var e=f.checkTurn()}else e=f.checkTurn(),p=f.checkNextPlayer();if("color"===
a.getFotogram())0===e?(!0===n?new CSelectColorPanel(a.getFotogram(),!0):new CSelectColorPanel(a.getFotogram()),f.nextTurn()):(l=this.onSelectColorCpu(e),f.nextTurn(),m.changeColor(l));else if("draw_four"===a.getFotogram())0===e?!0===n?new CSelectColorPanel(a.getFotogram(),!0):new CSelectColorPanel(a.getFotogram()):(l=this.onSelectColorCpu(e),d.refreshColor(l),m.drawFourAnim());else if("color"!==a.getFotogram()&&"draw_four"!==a.getFotogram()&&a.getSuit()===l||a.getRank()===k.getLastCard().getRank())if(10===
a.getRank())f.nextTurn(),f.nextTurn(),!0===n?setTimeout(function(){!0===n&&c.drawCards(0,2,0,!0);setTimeout(function(){m.stopTurn()},800)},2E3):m.stopTurn();else if(11===a.getRank())2<NUM_PLAYERS?(f.changeClockWise(),!0!==b?f.nextTurn():f.prevTurn()):(f.changeClockWise(),f.nextTurn(),f.nextTurn()),!0===n?setTimeout(function(){!0===n&&c.drawCards(0,2,0,!0);setTimeout(function(){m.changeClockWise(f.getClockWise())},1E3)},2E3):m.changeClockWise(f.getClockWise());else if(12===a.getRank())!0===n?setTimeout(function(){!0===
n&&c.drawCards(0,2,0,!0);setTimeout(function(){m.drawTwoAnim()},1E3)},2E3):m.drawTwoAnim();else if(10>a.getRank())if(f.nextTurn(),!0===n)setTimeout(function(){if(!0===n)c.drawCards(0,2,0,!0);else c.onNextTurn()},2E3);else this.onNextTurn()};this.onNextTurn=function(){if(!0!==this.checkGameOver())if(0===h.getLength()&&!1===A)A=!0,m.shuffleAnimation();else{this.setOffTurn();h.enableInputDraw();var a=f.checkTurn();e[a].setOnTurn(a);var b=k.getLastCard();if(0===a)this.onInputPlayer(),!0===this.onCheckDraw()&&
this.checkHelpDraw();else if(0!==a){var c=[];for(var d=0;d<e[a].getLength();d++)4===e[a].getCardByIndex(d).getSuit()||e[a].getCardByIndex(d).getRank()!==b.getRank()&&e[a].getCardByIndex(d).getSuit()!==l?"color"===e[a].getCardByIndex(d).getFotogram()?c.push({oCard:e[a].getCardByIndex(d),iValue:2}):"draw_four"===e[a].getCardByIndex(d).getFotogram()&&c.push({oCard:e[a].getCardByIndex(d),iValue:1}):12===e[a].getCardByIndex(d).getRank()?c.push({oCard:e[a].getCardByIndex(d),iValue:6}):10===e[a].getCardByIndex(d).getRank()?
c.push({oCard:e[a].getCardByIndex(d),iValue:5}):11===e[a].getCardByIndex(d).getRank()?c.push({oCard:e[a].getCardByIndex(d),iValue:4}):c.push({oCard:e[a].getCardByIndex(d),iValue:3});0===c.length?this.drawCards(a,1,1E3):(c.sort(function(a,b){return parseFloat(b.iValue)-parseFloat(a.iValue)}),this.cpuPickCard(c[0].oCard))}}};this.checkAvaiableDrawFour=function(){for(var a=!0,b,c=0;c<e[0].getLength();c++)if(b=e[0].getCardByIndex(c),b.getRank()===k.getLastCard().getRank()&&"draw_four"!==b.getFotogram()||
b.getSuit()===l||"color"===b.getFotogram())a=!1;return a};this.declareUNO=function(){!0===n&&(n=!1,e[0].checkUno())};this.drawCards=function(a,c,d,e){e&&(n=!1,(new createjs.Tween.get(z)).to({alpha:1},400).wait(4E3).to({alpha:0},400));b=c;this.drawCardsTween(a,c,d,e)};this.drawCardsTween=function(a,c,d,g){var n=this,p;v.addChildAt(w,v.numChildren);h.setOnTop();if(0===h.getLength()&&!1===A)A=!0,m.shuffleAnimation(a,c,d);else if(1===c){var q=k.getLastCard();p;var y=h.takeLastCard();y.setOnTop();var r=
e[a].getContainerPos();var t=e[a].getPosNewCard();var u=h.getGlobalPosition();(new createjs.Tween.get(y.getSprite())).wait(d).to({x:r.x+t.x-u.x,y:r.y+t.y-u.y},400,createjs.Ease.cubicOut).call(function(){e[a].pushCard(new CCard(e[a].getPosNewCard().x,e[a].getPosNewCard().y,e[a].getContainer(),y.getFotogram(),y.getRank(),y.getSuit()));y.unload();p=e[a].getLastCard();0===a?(p.showCard(),p.onSetTurned()):playSound("card",1,!1);e[a].centerContainer();p.getRank()===q.getRank()||p.getSuit()===l||"color"===
p.getFotogram()||"draw_four"===p.getFotogram()?0!==a&&(n.onNextTurn(),playSound("card",1,!1)):(e[a].centerContainer(),f.nextTurn(),n.onNextTurn())})}else q=k.getLastCard(),p,y=h.takeLastCard(),y.setOnTop(),r=e[a].getContainerPos(),t=e[a].getPosNewCard(),u=h.getGlobalPosition(),(new createjs.Tween.get(y.getSprite())).wait(d).to({x:r.x+t.x-u.x,y:r.y+t.y-u.y},400,createjs.Ease.cubicOut).call(function(){e[a].pushCard(new CCard(e[a].getPosNewCard().x,e[a].getPosNewCard().y,e[a].getContainer(),y.getFotogram(),
y.getRank(),y.getSuit()));y.unload();p=e[a].getLastCard();0===a?(p.showCard(),p.onSetTurned()):playSound("card",1,!1);e[a].centerContainer();b--;0<b?n.drawCardsTween(a,c,d,g):(g||(f.nextTurn(),f.nextTurn()),n.onNextTurn())})};this.onDraw=function(){h.disableInputDraw();q=!1;s_oStage.removeChild(t);var a=!0;if(0!==k.getLength()&&0===f.checkTurn()){for(var b=0;b<e[0].getLength();b++){var c=e[0].getCardByIndex(b);if(c.getRank()===k.getLastCard().getRank()||c.getSuit()===l||"color"===c.getFotogram()||
"draw_four"===c.getFotogram())a=!1}!0===a&&(this.drawCards(0,1),x=!1)}};this.onCheckDraw=function(){var a=!0;q=!0;if(0!==k.getLength()&&0===f.checkTurn()){for(var b=0;b<e[0].getLength();b++){var c=e[0].getCardByIndex(b);if(c.getRank()===k.getLastCard().getRank()||c.getSuit()===l||"color"===c.getFotogram()||"draw_four"===c.getFotogram())q=a=!1}x=!0===q&&0===f.checkTurn()?!0:!1;return a}};this.onSelectColor=function(a){l=a;d.refreshColor(l)};this.onInputPlayer=function(){for(var a=0;a<e[0].getLength();a++)e[0].getCardByIndex(a).onSetTurned()};
this.offInputPlayer=function(){for(var a=0;a<e[0].getLength();a++)e[0].getCardByIndex(a).offSetTurned()};this.onSelectColorCpu=function(a){for(var b,c=[{iColor:0,iPoints:0},{iColor:1,iPoints:0},{iColor:2,iPoints:0},{iColor:3,iPoints:0}],d=0;d<e[a].getLength();d++){b=e[a].getCardByIndex(d);for(var f=0;f<c.length;f++)b.getSuit()===f&&c[f].iPoints++}c.sort(function(a,b){return parseFloat(b.iPoints)-parseFloat(a.iPoints)});return c[0].iColor};this.onEndDrawFour=function(){this.drawCards(p,4,0)};this.onEndDrawTwo=
function(){this.drawCards(p,2,0)};this.getbUNO=function(){return n};this.checkGameOver=function(){var a=!1;0===e[0].getLength()&&(this.gameOver(0),a=!0);0===e[1].getLength()&&(this.gameOver(1),a=!0);e[2]&&0===e[2].getLength()&&(this.gameOver(2),a=!0);e[3]&&0===e[3].getLength()&&(this.gameOver(3),a=!0);return a};this.setOffTurn=function(){for(var a=0;a<NUM_PLAYERS;a++)e[a].setOffTurn(a)};this.checkNumOfCards=function(){if(0===h.getLength()){var a=k.removeAllCardUnderTheDeck();this.shuffle(a);for(var b=
0;b<a.length;b++)h.pushCard(new CCard(0,0,h.getContainer(),a[b].getFotogram(),a[b].getRank(),a[b].getSuit())),a[b].unload();A=!1}};this.onEndShuffle=function(a,c,d){this.checkNumOfCards();if(0!==b)this.drawCardsTween(a,c,d);else this.onNextTurn()};this.shuffle=function(a){var b;for(b=a.length;b;b--){var c=Math.floor(Math.random()*b);var d=a[b-1];a[b-1]=a[c];a[c]=d}};this.unload=function(){null!==g&&g.unload();d.unload();q=!1;createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=
function(){$(s_oMain).trigger("end_session");s_oGame.unload();s_oMain.gotoMenu()};this.stopFinger=function(){!0===q&&(q=!1)};this.gameOver=function(a){r=new createjs.Shape;r.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=0;r.on("mousedown",function(){});s_oStage.addChild(r);(new createjs.Tween.get(r)).to({alpha:.7},500);c=0===a?Math.floor(1/C*c):0;g=CEndPanel(s_oSpriteLibrary.getSprite("credits_panel"));g.show(c,a)};this.checkHelpDraw=function(){setTimeout(function(){!0===
q&&s_oStage.addChildAt(t,s_oStage.numChildren)},5E3)};this.onMouseOverDeck=function(a){s_bMobile||(a.target.cursor=!0===x?"pointer":"default")};this.update=function(){};s_oGame=this;STARTING_NUM_CARDS=a.starting_num_cards;this._init()}var s_oGame;
function CInterface(){var a,c,b,d,g,h,e,k,f,l,n,m,p,t,q=null,r=null,x,w;this._init=function(){w=new createjs.Container;var u=s_oSpriteLibrary.getSprite("but_exit");e=CANVAS_WIDTH-u.height/2-10;k=u.height/2+10;m=new CGfxButton(e,k,u,w);m.addEventListener(ON_MOUSE_UP,this._onExit,this);g=CANVAS_WIDTH-u.width/2-100;h=u.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=s_oSpriteLibrary.getSprite("audio_icon"),n=new CToggle(g,h,u,s_bAudioActive,w),n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);u=window.document;var v=u.documentElement;q=v.requestFullscreen||v.mozRequestFullScreen||v.webkitRequestFullScreen||v.msRequestFullscreen;r=u.exitFullscreen||u.mozCancelFullScreen||u.webkitExitFullscreen||u.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(q=!1);q&&!inIframe()&&(u=s_oSpriteLibrary.getSprite("but_fullscreen"),b=u.width/4+10,d=u.height/2+10,p=new CToggle(b,d,u,s_bFullscreen,w),p.addEventListener(ON_MOUSE_UP,this._onFullscreen,this));u=s_oSpriteLibrary.getSprite("but_uno");a=CANVAS_WIDTH/
2+222;c=CANVAS_HEIGHT/2+70;x=new CGfxButton(a,c,u,s_oStage);x.addEventListener(ON_MOUSE_UP,this._onButUno,this);u=s_oSpriteLibrary.getSprite("colors");u=new createjs.SpriteSheet({images:[u],frames:{width:103,height:102,regX:51.5,regY:51},animations:{red:[0],green:[1],blue:[2],yellow:[3]}});f=CANVAS_WIDTH/2+220;l=CANVAS_HEIGHT/2-60;t=new createjs.Sprite(u,0);t.stop();t.x=f;t.y=l;s_oStage.addChild(w);this.refreshButtonPos()};this.setButtonUno=function(a){x.setClickable(a)};this.refreshColor=function(a){t.gotoAndStop(a);
s_oStage.addChildAt(t,1)};this._onButUno=function(){s_oGame.declareUNO()};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n.unload(),n=null;m.unload();q&&!inIframe()&&p.unload();s_oInterface=null};this.refreshButtonPos=function(){m.setPosition(e-s_iOffsetX,s_iOffsetY+k);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||n.setPosition(g-s_iOffsetX,s_iOffsetY+h);q&&!inIframe()&&p.setPosition(b+s_iOffsetX,d+s_iOffsetY)};this.setOnTop=function(){s_oStage.addChildAt(w,s_oStage.numChildren)};
this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oGame.onExit)};this.resetFullscreenBut=function(){p.setActive(s_bFullscreen)};this._onFullscreen=function(){s_bFullscreen?r.call(window.document):q.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,c,b,d,g,h;this._init=function(){var e=this;g=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));var f=CANVAS_WIDTH/2,l=CANVAS_HEIGHT/2-200;c=new createjs.Text(TEXT_HELP1," 24px Arial","#000000");c.x=f+2;c.y=l+2;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=400;a=new createjs.Text(TEXT_HELP1," 24px Arial","#ffffff");a.x=f;a.y=l;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;f=CANVAS_WIDTH/2-130;l=CANVAS_HEIGHT/2-40;d=new createjs.Text(TEXT_HELP2,
" 24px Arial","#000000");d.x=f+2;d.y=l+2;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=280;b=new createjs.Text(TEXT_HELP2," 24px Arial","#ffffff");b.x=f;b.y=l;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=280;h=new createjs.Container;h.addChild(g,c,a,d,b);h.alpha=0;s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:1},700);h.on("pressup",function(){e._onExitHelp()})};this.unload=function(){s_oStage.removeChild(h);var a=this;h.off("pressup",function(){a._onExitHelp()})};
this._onExitHelp=function(){e.unload();s_oGame._onExitHelp()};var e=this;this._init()}
function CCreditsPanel(){var a,c,b,d,g;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);b=new createjs.Container;s_oStage.addChild(b);var h=s_oSpriteLibrary.getSprite("credits_panel"),e=createBitmap(h);e.regX=h.width/2;e.regY=h.height/2;b.addChild(e);b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT+h.height/2;a=b.y;(new createjs.Tween.get(b)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);e=new createjs.Text("DEVELOPED BY"," 20px "+PRIMARY_FONT,"#ffffff");e.y=-h.height/2+40;e.textAlign="center";e.textBaseline="middle";e.lineWidth=300;b.addChild(e);h=new createjs.Text("www.codethislab.com"," 30px "+PRIMARY_FONT,"#ffffff");h.y=100;h.textAlign="center";h.textBaseline="middle";h.lineWidth=500;b.addChild(h);h=s_oSpriteLibrary.getSprite("ctl_logo");g=createBitmap(h);g.on("mousedown",this._onLogoButRelease);g.regX=h.width/2;g.regY=h.height/2;b.addChild(g);
h=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(230,-107,h,b);d.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(b)).to({y:a},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(c);s_oStage.removeChild(b);d.unload()});c.off("mousedown",function(){});g.off("mousedown",this._onLogoButRelease)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en")};
this._onMoreGamesReleased=function(){window.open("http://codecanyon.net/collections/5409142-games")};this._init()}
function CSelectColorPanel(a,c){var b,d,g,h,e=this,k,f,l,n;this._init=function(){"color"===a&&playSound("special_card",.5,!1);e=this;d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;d.on("mousedown",function(){});s_oStage.addChild(d);(new createjs.Tween.get(d,{override:!0})).to({alpha:.7},500);g=new createjs.Container;s_oStage.addChild(g);h=new createjs.Container;g.addChild(h);var c=s_oSpriteLibrary.getSprite("select_color_panel"),p=createBitmap(c);
p.regX=c.width/2;p.regY=c.height/2;g.addChildAt(p,0);g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT+c.height/2;b=g.y;(new createjs.Tween.get(g,{override:!0})).to({y:CANVAS_HEIGHT/2-40},600,createjs.Ease.backOut);p=new createjs.Text(TEXT_SELECT_COLOR," 45px "+PRIMARY_FONT,"#ffffff");p.y=-c.height/2+90;p.textAlign="center";p.textBaseline="middle";p.lineWidth=400;g.addChild(p);h.y=g.getBounds().height/5;c=s_oSpriteLibrary.getSprite("but_red");k=new CGfxButton(-190,-20,c,h);k.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(0);
h});c=s_oSpriteLibrary.getSprite("but_green");f=new CGfxButton(-65,-20,c,h);f.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(1);h});c=s_oSpriteLibrary.getSprite("but_blue");l=new CGfxButton(65,-20,c,h);l.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(2);h});c=s_oSpriteLibrary.getSprite("but_yellow");n=new CGfxButton(190,-20,c,h);n.addEventListener(ON_MOUSE_UP,function(){e.onSelectColor(3);h})};this.onSelectColor=function(a){s_oGame.onSelectColor(a);e.unload()};this.unload=function(){"color"===
a?((new createjs.Tween.get(d,{override:!0})).to({alpha:0},500),(new createjs.Tween.get(g,{override:!0})).to({y:b},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d,{override:!0});s_oStage.removeChild(g,{override:!0});if(c)setTimeout(function(){if(!0===s_oGame.getbUNO())s_oGame.drawCards(0,2,0,c);else s_oGame.onNextTurn()},2E3);else s_oGame.onNextTurn()})):((new createjs.Tween.get(d,{override:!0})).to({alpha:0},500),(new createjs.Tween.get(g,{override:!0})).to({y:b},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);
s_oStage.removeChild(g);c?setTimeout(function(){!0===s_oGame.getbUNO()&&s_oGame.drawCards(0,2,0,c);setTimeout(function(){s_oCAnimation.drawFourAnim()},1E3)},2E3):s_oCAnimation.drawFourAnim()}));d.off("mousedown",function(){})};this._init()}
function CAreYouSurePanel(a){var c,b,d,g,h;this._init=function(a){s_oGame.stopFinger();g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;g.on("mousedown",function(){});s_oStage.addChild(g);(new createjs.Tween.get(g)).to({alpha:.7},500);h=new createjs.Container;s_oStage.addChildAt(h,s_oStage.numChildren);a=s_oSpriteLibrary.getSprite("credits_panel");var e=createBitmap(a);e.regX=a.width/2;e.regY=a.height/2;h.addChild(e);h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT+
a.height/2;c=h.y;(new createjs.Tween.get(h)).to({y:CANVAS_HEIGHT/2-40},500,createjs.Ease.quartIn).call(function(){createjs.Ticker.paused=!0});e=new createjs.Text(TEXT_ARE_SURE," 44px "+PRIMARY_FONT,"#000000");e.y=-a.height/2+95;e.textAlign="center";e.textBaseline="middle";e.lineWidth=400;e.outline=5;h.addChild(e);a=new createjs.Text(TEXT_ARE_SURE," 44px "+PRIMARY_FONT,"#FFFFFF");a.y=e.y;a.textAlign="center";a.textBaseline="middle";a.lineWidth=400;h.addChild(a);b=new CGfxButton(110,80,s_oSpriteLibrary.getSprite("but_yes_big"),
h);b.addEventListener(ON_MOUSE_UP,this._onButYes,this);d=new CGfxButton(-110,80,s_oSpriteLibrary.getSprite("but_exit_big"),h);d.addEventListener(ON_MOUSE_UP,this._onButNo,this)};this._onButYes=function(){d.setClickable(!1);b.setClickable(!1);createjs.Ticker.paused=!1;(new createjs.Tween.get(g)).to({alpha:0},500);(new createjs.Tween.get(h)).to({y:c},400,createjs.Ease.backIn).call(function(){a();e.unload()})};this._onButNo=function(){createjs.Ticker.paused=!1;d.setClickable(!1);b.setClickable(!1);(new createjs.Tween.get(g)).to({alpha:0},
500);(new createjs.Tween.get(h)).to({y:c},400,createjs.Ease.backIn).call(function(){e.unload()})};this.unload=function(){d.unload();b.unload();s_oStage.removeChild(g);s_oStage.removeChild(h);g.off("mousedown",function(){})};var e=this;this._init(a)}
function CEndPanel(a){var c,b,d,g,h,e,k,f,l;this._init=function(a){c=createBitmap(a);a=c.getBounds();c.regX=a.width/2;c.regY=a.height/2;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;d=new createjs.Text(""," 50px "+PRIMARY_FONT,"#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2-30;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=550;g=new createjs.Text(""," 50px "+PRIMARY_FONT,"#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-28;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=550;h=
new createjs.Text(""," 35px "+PRIMARY_FONT,"#000");h.x=CANVAS_WIDTH/2+1;h.y=CANVAS_HEIGHT/2+120;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=550;e=new createjs.Text(""," 35px "+PRIMARY_FONT,"#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+110;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=550;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,h,e,d,g);s_oStage.addChild(b);a=s_oSpriteLibrary.getSprite("but_restart");f=new CGfxButton(CANVAS_WIDTH/2+60,CANVAS_HEIGHT/
2+180,a,b);a=s_oSpriteLibrary.getSprite("but_home");l=new CGfxButton(CANVAS_WIDTH/2-60,CANVAS_HEIGHT/2+180,a,b)};this.unload=function(){};this._initListener=function(){l.addEventListener(ON_MOUSE_DOWN,this._onExit,this);f.addEventListener(ON_MOUSE_DOWN,this._onRestart,this)};this.show=function(a,c){playSound("game_over",1,!1);k=a;var f=c+1;0===c?(d.text=TEXT_GAMEOVER,g.text=TEXT_GAMEOVER,g.y=CANVAS_HEIGHT/2-30,d.y=CANVAS_HEIGHT/2-28):(k=a=0,d.text=TEXT_LOSE+f+TEXT_LOSE2,g.text=TEXT_LOSE+f+TEXT_LOSE2);
h.text=TEXT_SCORE+": "+a;e.text=TEXT_SCORE+": "+a;b.visible=!0;var l=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){l._initListener()});$(s_oMain).trigger("save_score",a);$(s_oMain).trigger("show_interlevel_ad");$(s_oMain).trigger("end_session")};this._onExit=function(){$(s_oMain).trigger("share_event",k);b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.unload();s_oMain.gotoMenu()};this._onRestart=function(){s_oGame.unload();s_oMain.gotoGame(!1);s_oStage.removeChild(b)};
this._init(a);return this};
