define(function(require, exports, module) {

	var config = Object.freeze({

		CACHEBUST: "1",

		SEIDR_HOST_URI: "",
		SEIDR_PRODUCT_ID: 7,

		ENABLE_DESIGNER_TOOLS: false,
		ENABLE_PROMISE_DEBUGGER: false,
		ENABLE_EVENT_TRACING: false,
		ENABLE_GL_PROFILING: false,
		ENABLE_CURRENCY_DROPS: true,
		ENABLE_FACEBOOK: false,
		ENABLE_METRICS: false,
		ENABLE_FPS_METER: false,
		ENABLE_DEBUG_OVERLAY: false,

		REFERENCE_VIEWPORT_WIDTH_IN_PIXELS: 1280,
		REFERENCE_VIEWPORT_HEIGHT_IN_PIXELS: 1920,
		REFERENCE_ASSET_SIZE: 2,
		REFERENCE_DEVICE_PIXEL_RATIO: 2,

		MAXIMUM_POINT_SCALE: 0.5,
		MAXIMUM_POINT_SCALE_HI_RES: 1,
		MAXIMUM_ASPECT_RATIO: (640/1136),
		MINIMUM_ASPECT_RATIO: (640/1136),

		MAX_VIEWPORT_WIDTH_HI_RES: 1536,
		MAX_VIEWPORT_HEIGHT_HI_RES: 2732,
		MIN_VIEWPORT_WIDTH_DESKTOP: 320,
		MIN_VIEWPORT_HEIGHT_DESKTOP: 480,

		ENABLE_WEBGL: true,

		KIK_BOT_USERNAME: "galatronvs",

		GA_KEY: "UA-41145067-11",

		logging: {
			"root": "LOG"
		},

		REST_SERVER_URL: ""

	});

	module.exports = config;

});
